
name: "tagged-release"

on:
  push:
    branches:
      - testReleases
    paths:
      - 'CHANGELOG.md'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - name: Extract Version from Changelog
        run: |
          echo "version=$(awk '/### /{print $2;exit}' CHANGELOG.md)" >> $GITHUB_ENV


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            plugin_manager.py
          automatic_release_tag: "latest"
          title: "V$version"
