name: Automated Releases

on:
  push:
    branches:
      - testReleases
    paths:
      - 'CHANGELOG.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install github-release
      run: |
        curl -sSL https://github.com/github-release/github-release/releases/download/v0.10.0/linux-amd64-github-release.bz2 -o github-release.bz2
        bzip2 -d github-release.bz2
        chmod +x github-release
        sudo mv github-release /usr/local/bin/

    - name: Extract Version from Changelog
      id: extract_version
      run: echo "name=version::$(awk '/### \[Version\]/{print $3;exit}' CHANGELOG.md)" >> GITHUB_OUTPUT

    - name: Generate Release
      run: |
        version=${{ steps.extract_version.outputs.version }}

        # Extract the changelog since the last release
        changelog=$(sed -n -e "/### \[Version\] $version/,/${{ github.sha }}/p" CHANGELOG.md)

        # Create a release with the version
        github-release release \
          --repo ${{ github.repository }} \
          --tag $version \
          --name "Release $version" \
          --description "$changelog" 

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
