# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    branches:
      - testReleases


# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/create-release@v1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          release_name: "Release ${{ github.run_number}}"
